### ISSUE TITLE
valmi-activation Repository Shutdown Exception

### ISSUE THREAD

**Issue by rajvarkala** [valmi-io/valmi-activation#23]
05/25/2023 03:21:38 PM INFO     JobCreator                         requests::execute              >>> {"query": "mutation ($repositoryLocationName: String!) {\n  shutdownRepositoryLocation(repositoryLocationName: $repositoryLocationName) {\n    __typename\n    ... on PythonError {\n      message\n    }\n    ... on RepositoryLocationNotFound {\n      message\n    }\n  }\n}", "variables": {"repositoryLocationName": "valmi-repo"}}
05/25/2023 03:21:38 PM DEBUG    JobCreator                   connectionpool::_new_conn            Starting new HTTP connection (1): dagit:3000
05/25/2023 03:21:38 PM ERROR    SyncRunner                      run_manager::_run                 Error while handling syncs in run manager
Traceback (most recent call last):
  File "/opt/valmi-activation/lib/python3.10/site-packages/dagster_graphql/client/client.py", line 98, in _execute
    return self._client.execute(gql(query), variable_values=variables)
  File "/opt/valmi-activation/lib/python3.10/site-packages/gql/client.py", line 403, in execute
    return self.execute_sync(
  File "/opt/valmi-activation/lib/python3.10/site-packages/gql/client.py", line 220, in execute_sync
    with self as session:
  File "/opt/valmi-activation/lib/python3.10/site-packages/gql/client.py", line 702, in __enter__
    return self.connect_sync()
  File "/opt/valmi-activation/lib/python3.10/site-packages/gql/client.py", line 678, in connect_sync
    self.transport.connect()
  File "/opt/valmi-activation/lib/python3.10/site-packages/gql/transport/requests.py", line 106, in connect
    raise TransportAlreadyConnected("Transport is already connected")
gql.transport.exceptions.TransportAlreadyConnected: Transport is already connected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/src/./orchestrator/run_manager.py", line 106, in _run
    dagster_run_id = self.dc.submit_job_execution(
  File "/opt/valmi-activation/lib/python3.10/site-packages/dagster_graphql/client/client.py", line 319, in submit_job_execution
    return self._core_submit_execution(
  File "/opt/valmi-activation/lib/python3.10/site-packages/dagster_graphql/client/client.py", line 149, in _core_submit_execution
    pipeline_info_lst = self._get_repo_locations_and_names_with_pipeline(pipeline_name)
  File "/opt/valmi-activation/lib/python3.10/site-packages/dagster_graphql/client/client.py", line 106, in _get_repo_locations_and_names_with_pipeline
    res_data = self._execute(CLIENT_GET_REPO_LOCATIONS_NAMES_AND_PIPELINES_QUERY)
  File "/opt/valmi-activation/lib/python3.10/site-packages/dagster_graphql/client/client.py", line 100, in _execute
    raise DagsterGraphQLClientError(
dagster_graphql.client.utils.DagsterGraphQLClientError: Exception occured during execution of query 

query {
  repositoriesOrError {
    __typename
    ... on RepositoryConnection {
      nodes {
        name
        location {
          name
        }
        pipelines {
          name
        }
      }
    }
    ... on PythonError {
      message
    }
  }
}

 with variables 
None

05/25/2023 03:21:38 PM ERROR    SyncRunner                 retry_decorators::wrapper              Failure _run due to error: Exception occured during execution of query 

query {
  repositoriesOrError {
    __typename
    ... on RepositoryConnection {
      nodes {
        name
        location {
          name
        }
        pipelines {
          name
        }
      }
    }
    ... on PythonError {
      message
    }
  }
}

 with variables 
None

**Comment by rajvarkala** [comment]
Fixed
